package com.atguigu.springboot.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TAppletInformateExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_applet_informate
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_applet_informate
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_applet_informate
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_applet_informate
     *
     * @mbg.generated
     */
    public TAppletInformateExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_applet_informate
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_applet_informate
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_applet_informate
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_applet_informate
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_applet_informate
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_applet_informate
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_applet_informate
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_applet_informate
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_applet_informate
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_applet_informate
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_applet_informate
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAppletNameIsNull() {
            addCriterion("applet_name is null");
            return (Criteria) this;
        }

        public Criteria andAppletNameIsNotNull() {
            addCriterion("applet_name is not null");
            return (Criteria) this;
        }

        public Criteria andAppletNameEqualTo(String value) {
            addCriterion("applet_name =", value, "appletName");
            return (Criteria) this;
        }

        public Criteria andAppletNameNotEqualTo(String value) {
            addCriterion("applet_name <>", value, "appletName");
            return (Criteria) this;
        }

        public Criteria andAppletNameGreaterThan(String value) {
            addCriterion("applet_name >", value, "appletName");
            return (Criteria) this;
        }

        public Criteria andAppletNameGreaterThanOrEqualTo(String value) {
            addCriterion("applet_name >=", value, "appletName");
            return (Criteria) this;
        }

        public Criteria andAppletNameLessThan(String value) {
            addCriterion("applet_name <", value, "appletName");
            return (Criteria) this;
        }

        public Criteria andAppletNameLessThanOrEqualTo(String value) {
            addCriterion("applet_name <=", value, "appletName");
            return (Criteria) this;
        }

        public Criteria andAppletNameLike(String value) {
            addCriterion("applet_name like", value, "appletName");
            return (Criteria) this;
        }

        public Criteria andAppletNameNotLike(String value) {
            addCriterion("applet_name not like", value, "appletName");
            return (Criteria) this;
        }

        public Criteria andAppletNameIn(List<String> values) {
            addCriterion("applet_name in", values, "appletName");
            return (Criteria) this;
        }

        public Criteria andAppletNameNotIn(List<String> values) {
            addCriterion("applet_name not in", values, "appletName");
            return (Criteria) this;
        }

        public Criteria andAppletNameBetween(String value1, String value2) {
            addCriterion("applet_name between", value1, value2, "appletName");
            return (Criteria) this;
        }

        public Criteria andAppletNameNotBetween(String value1, String value2) {
            addCriterion("applet_name not between", value1, value2, "appletName");
            return (Criteria) this;
        }

        public Criteria andLogoUrlIsNull() {
            addCriterion("logo_url is null");
            return (Criteria) this;
        }

        public Criteria andLogoUrlIsNotNull() {
            addCriterion("logo_url is not null");
            return (Criteria) this;
        }

        public Criteria andLogoUrlEqualTo(String value) {
            addCriterion("logo_url =", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlNotEqualTo(String value) {
            addCriterion("logo_url <>", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlGreaterThan(String value) {
            addCriterion("logo_url >", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlGreaterThanOrEqualTo(String value) {
            addCriterion("logo_url >=", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlLessThan(String value) {
            addCriterion("logo_url <", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlLessThanOrEqualTo(String value) {
            addCriterion("logo_url <=", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlLike(String value) {
            addCriterion("logo_url like", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlNotLike(String value) {
            addCriterion("logo_url not like", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlIn(List<String> values) {
            addCriterion("logo_url in", values, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlNotIn(List<String> values) {
            addCriterion("logo_url not in", values, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlBetween(String value1, String value2) {
            addCriterion("logo_url between", value1, value2, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlNotBetween(String value1, String value2) {
            addCriterion("logo_url not between", value1, value2, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andButtomLogoUrlIsNull() {
            addCriterion("buttom_logo_url is null");
            return (Criteria) this;
        }

        public Criteria andButtomLogoUrlIsNotNull() {
            addCriterion("buttom_logo_url is not null");
            return (Criteria) this;
        }

        public Criteria andButtomLogoUrlEqualTo(String value) {
            addCriterion("buttom_logo_url =", value, "buttomLogoUrl");
            return (Criteria) this;
        }

        public Criteria andButtomLogoUrlNotEqualTo(String value) {
            addCriterion("buttom_logo_url <>", value, "buttomLogoUrl");
            return (Criteria) this;
        }

        public Criteria andButtomLogoUrlGreaterThan(String value) {
            addCriterion("buttom_logo_url >", value, "buttomLogoUrl");
            return (Criteria) this;
        }

        public Criteria andButtomLogoUrlGreaterThanOrEqualTo(String value) {
            addCriterion("buttom_logo_url >=", value, "buttomLogoUrl");
            return (Criteria) this;
        }

        public Criteria andButtomLogoUrlLessThan(String value) {
            addCriterion("buttom_logo_url <", value, "buttomLogoUrl");
            return (Criteria) this;
        }

        public Criteria andButtomLogoUrlLessThanOrEqualTo(String value) {
            addCriterion("buttom_logo_url <=", value, "buttomLogoUrl");
            return (Criteria) this;
        }

        public Criteria andButtomLogoUrlLike(String value) {
            addCriterion("buttom_logo_url like", value, "buttomLogoUrl");
            return (Criteria) this;
        }

        public Criteria andButtomLogoUrlNotLike(String value) {
            addCriterion("buttom_logo_url not like", value, "buttomLogoUrl");
            return (Criteria) this;
        }

        public Criteria andButtomLogoUrlIn(List<String> values) {
            addCriterion("buttom_logo_url in", values, "buttomLogoUrl");
            return (Criteria) this;
        }

        public Criteria andButtomLogoUrlNotIn(List<String> values) {
            addCriterion("buttom_logo_url not in", values, "buttomLogoUrl");
            return (Criteria) this;
        }

        public Criteria andButtomLogoUrlBetween(String value1, String value2) {
            addCriterion("buttom_logo_url between", value1, value2, "buttomLogoUrl");
            return (Criteria) this;
        }

        public Criteria andButtomLogoUrlNotBetween(String value1, String value2) {
            addCriterion("buttom_logo_url not between", value1, value2, "buttomLogoUrl");
            return (Criteria) this;
        }

        public Criteria andRegisterPageIsNull() {
            addCriterion("register_page is null");
            return (Criteria) this;
        }

        public Criteria andRegisterPageIsNotNull() {
            addCriterion("register_page is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterPageEqualTo(String value) {
            addCriterion("register_page =", value, "registerPage");
            return (Criteria) this;
        }

        public Criteria andRegisterPageNotEqualTo(String value) {
            addCriterion("register_page <>", value, "registerPage");
            return (Criteria) this;
        }

        public Criteria andRegisterPageGreaterThan(String value) {
            addCriterion("register_page >", value, "registerPage");
            return (Criteria) this;
        }

        public Criteria andRegisterPageGreaterThanOrEqualTo(String value) {
            addCriterion("register_page >=", value, "registerPage");
            return (Criteria) this;
        }

        public Criteria andRegisterPageLessThan(String value) {
            addCriterion("register_page <", value, "registerPage");
            return (Criteria) this;
        }

        public Criteria andRegisterPageLessThanOrEqualTo(String value) {
            addCriterion("register_page <=", value, "registerPage");
            return (Criteria) this;
        }

        public Criteria andRegisterPageLike(String value) {
            addCriterion("register_page like", value, "registerPage");
            return (Criteria) this;
        }

        public Criteria andRegisterPageNotLike(String value) {
            addCriterion("register_page not like", value, "registerPage");
            return (Criteria) this;
        }

        public Criteria andRegisterPageIn(List<String> values) {
            addCriterion("register_page in", values, "registerPage");
            return (Criteria) this;
        }

        public Criteria andRegisterPageNotIn(List<String> values) {
            addCriterion("register_page not in", values, "registerPage");
            return (Criteria) this;
        }

        public Criteria andRegisterPageBetween(String value1, String value2) {
            addCriterion("register_page between", value1, value2, "registerPage");
            return (Criteria) this;
        }

        public Criteria andRegisterPageNotBetween(String value1, String value2) {
            addCriterion("register_page not between", value1, value2, "registerPage");
            return (Criteria) this;
        }

        public Criteria andIsForminpIsNull() {
            addCriterion("is_forminp is null");
            return (Criteria) this;
        }

        public Criteria andIsForminpIsNotNull() {
            addCriterion("is_forminp is not null");
            return (Criteria) this;
        }

        public Criteria andIsForminpEqualTo(String value) {
            addCriterion("is_forminp =", value, "isForminp");
            return (Criteria) this;
        }

        public Criteria andIsForminpNotEqualTo(String value) {
            addCriterion("is_forminp <>", value, "isForminp");
            return (Criteria) this;
        }

        public Criteria andIsForminpGreaterThan(String value) {
            addCriterion("is_forminp >", value, "isForminp");
            return (Criteria) this;
        }

        public Criteria andIsForminpGreaterThanOrEqualTo(String value) {
            addCriterion("is_forminp >=", value, "isForminp");
            return (Criteria) this;
        }

        public Criteria andIsForminpLessThan(String value) {
            addCriterion("is_forminp <", value, "isForminp");
            return (Criteria) this;
        }

        public Criteria andIsForminpLessThanOrEqualTo(String value) {
            addCriterion("is_forminp <=", value, "isForminp");
            return (Criteria) this;
        }

        public Criteria andIsForminpLike(String value) {
            addCriterion("is_forminp like", value, "isForminp");
            return (Criteria) this;
        }

        public Criteria andIsForminpNotLike(String value) {
            addCriterion("is_forminp not like", value, "isForminp");
            return (Criteria) this;
        }

        public Criteria andIsForminpIn(List<String> values) {
            addCriterion("is_forminp in", values, "isForminp");
            return (Criteria) this;
        }

        public Criteria andIsForminpNotIn(List<String> values) {
            addCriterion("is_forminp not in", values, "isForminp");
            return (Criteria) this;
        }

        public Criteria andIsForminpBetween(String value1, String value2) {
            addCriterion("is_forminp between", value1, value2, "isForminp");
            return (Criteria) this;
        }

        public Criteria andIsForminpNotBetween(String value1, String value2) {
            addCriterion("is_forminp not between", value1, value2, "isForminp");
            return (Criteria) this;
        }

        public Criteria andCommercialIdIsNull() {
            addCriterion("commercial_id is null");
            return (Criteria) this;
        }

        public Criteria andCommercialIdIsNotNull() {
            addCriterion("commercial_id is not null");
            return (Criteria) this;
        }

        public Criteria andCommercialIdEqualTo(String value) {
            addCriterion("commercial_id =", value, "commercialId");
            return (Criteria) this;
        }

        public Criteria andCommercialIdNotEqualTo(String value) {
            addCriterion("commercial_id <>", value, "commercialId");
            return (Criteria) this;
        }

        public Criteria andCommercialIdGreaterThan(String value) {
            addCriterion("commercial_id >", value, "commercialId");
            return (Criteria) this;
        }

        public Criteria andCommercialIdGreaterThanOrEqualTo(String value) {
            addCriterion("commercial_id >=", value, "commercialId");
            return (Criteria) this;
        }

        public Criteria andCommercialIdLessThan(String value) {
            addCriterion("commercial_id <", value, "commercialId");
            return (Criteria) this;
        }

        public Criteria andCommercialIdLessThanOrEqualTo(String value) {
            addCriterion("commercial_id <=", value, "commercialId");
            return (Criteria) this;
        }

        public Criteria andCommercialIdLike(String value) {
            addCriterion("commercial_id like", value, "commercialId");
            return (Criteria) this;
        }

        public Criteria andCommercialIdNotLike(String value) {
            addCriterion("commercial_id not like", value, "commercialId");
            return (Criteria) this;
        }

        public Criteria andCommercialIdIn(List<String> values) {
            addCriterion("commercial_id in", values, "commercialId");
            return (Criteria) this;
        }

        public Criteria andCommercialIdNotIn(List<String> values) {
            addCriterion("commercial_id not in", values, "commercialId");
            return (Criteria) this;
        }

        public Criteria andCommercialIdBetween(String value1, String value2) {
            addCriterion("commercial_id between", value1, value2, "commercialId");
            return (Criteria) this;
        }

        public Criteria andCommercialIdNotBetween(String value1, String value2) {
            addCriterion("commercial_id not between", value1, value2, "commercialId");
            return (Criteria) this;
        }

        public Criteria andCommercialKeyIsNull() {
            addCriterion("commercial_key is null");
            return (Criteria) this;
        }

        public Criteria andCommercialKeyIsNotNull() {
            addCriterion("commercial_key is not null");
            return (Criteria) this;
        }

        public Criteria andCommercialKeyEqualTo(String value) {
            addCriterion("commercial_key =", value, "commercialKey");
            return (Criteria) this;
        }

        public Criteria andCommercialKeyNotEqualTo(String value) {
            addCriterion("commercial_key <>", value, "commercialKey");
            return (Criteria) this;
        }

        public Criteria andCommercialKeyGreaterThan(String value) {
            addCriterion("commercial_key >", value, "commercialKey");
            return (Criteria) this;
        }

        public Criteria andCommercialKeyGreaterThanOrEqualTo(String value) {
            addCriterion("commercial_key >=", value, "commercialKey");
            return (Criteria) this;
        }

        public Criteria andCommercialKeyLessThan(String value) {
            addCriterion("commercial_key <", value, "commercialKey");
            return (Criteria) this;
        }

        public Criteria andCommercialKeyLessThanOrEqualTo(String value) {
            addCriterion("commercial_key <=", value, "commercialKey");
            return (Criteria) this;
        }

        public Criteria andCommercialKeyLike(String value) {
            addCriterion("commercial_key like", value, "commercialKey");
            return (Criteria) this;
        }

        public Criteria andCommercialKeyNotLike(String value) {
            addCriterion("commercial_key not like", value, "commercialKey");
            return (Criteria) this;
        }

        public Criteria andCommercialKeyIn(List<String> values) {
            addCriterion("commercial_key in", values, "commercialKey");
            return (Criteria) this;
        }

        public Criteria andCommercialKeyNotIn(List<String> values) {
            addCriterion("commercial_key not in", values, "commercialKey");
            return (Criteria) this;
        }

        public Criteria andCommercialKeyBetween(String value1, String value2) {
            addCriterion("commercial_key between", value1, value2, "commercialKey");
            return (Criteria) this;
        }

        public Criteria andCommercialKeyNotBetween(String value1, String value2) {
            addCriterion("commercial_key not between", value1, value2, "commercialKey");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("update_user like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("update_user not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNull() {
            addCriterion("is_delete is null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIsNotNull() {
            addCriterion("is_delete is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeleteEqualTo(String value) {
            addCriterion("is_delete =", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotEqualTo(String value) {
            addCriterion("is_delete <>", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThan(String value) {
            addCriterion("is_delete >", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteGreaterThanOrEqualTo(String value) {
            addCriterion("is_delete >=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThan(String value) {
            addCriterion("is_delete <", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLessThanOrEqualTo(String value) {
            addCriterion("is_delete <=", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteLike(String value) {
            addCriterion("is_delete like", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotLike(String value) {
            addCriterion("is_delete not like", value, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteIn(List<String> values) {
            addCriterion("is_delete in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotIn(List<String> values) {
            addCriterion("is_delete not in", values, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteBetween(String value1, String value2) {
            addCriterion("is_delete between", value1, value2, "isDelete");
            return (Criteria) this;
        }

        public Criteria andIsDeleteNotBetween(String value1, String value2) {
            addCriterion("is_delete not between", value1, value2, "isDelete");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_applet_informate
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_applet_informate
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}