package com.atguigu.springboot.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_applet_informate
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class TAppletInformate implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_applet_informate.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_applet_informate.applet_name
     *
     * @mbg.generated
     */
    private String appletName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_applet_informate.logo_url
     *
     * @mbg.generated
     */
    private String logoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_applet_informate.buttom_logo_url
     *
     * @mbg.generated
     */
    private String buttomLogoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_applet_informate.register_page
     *
     * @mbg.generated
     */
    private String registerPage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_applet_informate.is_forminp
     *
     * @mbg.generated
     */
    private String isForminp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_applet_informate.commercial_id
     *
     * @mbg.generated
     */
    private String commercialId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_applet_informate.commercial_key
     *
     * @mbg.generated
     */
    private String commercialKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_applet_informate.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_applet_informate.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_applet_informate.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_applet_informate.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_applet_informate.is_delete
     *
     * @mbg.generated
     */
    private String isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_applet_informate
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_applet_informate.id
     *
     * @return the value of t_applet_informate.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_applet_informate.id
     *
     * @param id the value for t_applet_informate.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_applet_informate.applet_name
     *
     * @return the value of t_applet_informate.applet_name
     *
     * @mbg.generated
     */
    public String getAppletName() {
        return appletName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_applet_informate.applet_name
     *
     * @param appletName the value for t_applet_informate.applet_name
     *
     * @mbg.generated
     */
    public void setAppletName(String appletName) {
        this.appletName = appletName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_applet_informate.logo_url
     *
     * @return the value of t_applet_informate.logo_url
     *
     * @mbg.generated
     */
    public String getLogoUrl() {
        return logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_applet_informate.logo_url
     *
     * @param logoUrl the value for t_applet_informate.logo_url
     *
     * @mbg.generated
     */
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_applet_informate.buttom_logo_url
     *
     * @return the value of t_applet_informate.buttom_logo_url
     *
     * @mbg.generated
     */
    public String getButtomLogoUrl() {
        return buttomLogoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_applet_informate.buttom_logo_url
     *
     * @param buttomLogoUrl the value for t_applet_informate.buttom_logo_url
     *
     * @mbg.generated
     */
    public void setButtomLogoUrl(String buttomLogoUrl) {
        this.buttomLogoUrl = buttomLogoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_applet_informate.register_page
     *
     * @return the value of t_applet_informate.register_page
     *
     * @mbg.generated
     */
    public String getRegisterPage() {
        return registerPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_applet_informate.register_page
     *
     * @param registerPage the value for t_applet_informate.register_page
     *
     * @mbg.generated
     */
    public void setRegisterPage(String registerPage) {
        this.registerPage = registerPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_applet_informate.is_forminp
     *
     * @return the value of t_applet_informate.is_forminp
     *
     * @mbg.generated
     */
    public String getIsForminp() {
        return isForminp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_applet_informate.is_forminp
     *
     * @param isForminp the value for t_applet_informate.is_forminp
     *
     * @mbg.generated
     */
    public void setIsForminp(String isForminp) {
        this.isForminp = isForminp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_applet_informate.commercial_id
     *
     * @return the value of t_applet_informate.commercial_id
     *
     * @mbg.generated
     */
    public String getCommercialId() {
        return commercialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_applet_informate.commercial_id
     *
     * @param commercialId the value for t_applet_informate.commercial_id
     *
     * @mbg.generated
     */
    public void setCommercialId(String commercialId) {
        this.commercialId = commercialId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_applet_informate.commercial_key
     *
     * @return the value of t_applet_informate.commercial_key
     *
     * @mbg.generated
     */
    public String getCommercialKey() {
        return commercialKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_applet_informate.commercial_key
     *
     * @param commercialKey the value for t_applet_informate.commercial_key
     *
     * @mbg.generated
     */
    public void setCommercialKey(String commercialKey) {
        this.commercialKey = commercialKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_applet_informate.create_time
     *
     * @return the value of t_applet_informate.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_applet_informate.create_time
     *
     * @param createTime the value for t_applet_informate.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_applet_informate.create_user
     *
     * @return the value of t_applet_informate.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_applet_informate.create_user
     *
     * @param createUser the value for t_applet_informate.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_applet_informate.update_time
     *
     * @return the value of t_applet_informate.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_applet_informate.update_time
     *
     * @param updateTime the value for t_applet_informate.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_applet_informate.update_user
     *
     * @return the value of t_applet_informate.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_applet_informate.update_user
     *
     * @param updateUser the value for t_applet_informate.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_applet_informate.is_delete
     *
     * @return the value of t_applet_informate.is_delete
     *
     * @mbg.generated
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_applet_informate.is_delete
     *
     * @param isDelete the value for t_applet_informate.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }
}