package com.atguigu.springboot.mapper;

import com.atguigu.springboot.entity.TAppletInformate;
import com.atguigu.springboot.entity.TAppletInformateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TAppletInformateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_applet_informate
     *
     * @mbg.generated
     */
    long countByExample(TAppletInformateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_applet_informate
     *
     * @mbg.generated
     */
    int deleteByExample(TAppletInformateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_applet_informate
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_applet_informate
     *
     * @mbg.generated
     */
    int insert(TAppletInformate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_applet_informate
     *
     * @mbg.generated
     */
    int insertSelective(TAppletInformate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_applet_informate
     *
     * @mbg.generated
     */
    List<TAppletInformate> selectByExample(TAppletInformateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_applet_informate
     *
     * @mbg.generated
     */
    TAppletInformate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_applet_informate
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TAppletInformate record, @Param("example") TAppletInformateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_applet_informate
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TAppletInformate record, @Param("example") TAppletInformateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_applet_informate
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TAppletInformate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_applet_informate
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TAppletInformate record);
}